locale: en-US
title: "Codela Blog"
description: "Everything you need to prepare for your technical interview"
baseurl: ""
url: "https://blog.codela.io"

date_format: "%B %-d, %Y"
read_time: true
words_per_minute: # 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

disqus:
  shortname: "codela"

google_analytics: "UA-2011187-2"
google_site_verification: "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y"

logo: "/images/codela-logo-square-padding.png"
twitter:
  username: "heycodela"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Generic Site Author
author:
  name: Codela Team
  picture: /images/codela-logo-square-padding.png
  email: hi@codela.io
  twitter: heycodela
  links:
    - title: Twitter
      url: https://www.twitter.com/heycodela
      icon: fab fa-twitter-square
    - title: LinkedIn
      url: https://www.linkedin.com/company/codela/
      icon: fab fa-linkedin
    - title: Facebook
      url: https://www.facebook/heycodela
      icon: fab fa-facebook-square
    - title: GitHub
      url: https://www.github.com/codela
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://www.twitter.com/heycodela
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://www.linkedin.com/company/codela/
    icon: fab fa-linkedin
  - title: Facebook
    url: https://www.facebook/heycodela
    icon: fab fa-facebook-square
  - title: GitHub
    url: https://www.github.com/codela
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
